vich_uploader:
    db_driver: orm

    mappings:
        user_img:
            uri_prefix: /images/user_img
            upload_destination: '%kernel.project_dir%/public/images/user_img'
        album_img:
            uri_prefix: /images/album_img
            upload_destination: '%kernel.project_dir%/public/images/album_img'
        event_img:
            uri_prefix: /images/event_img
            upload_destination: '%kernel.project_dir%/public/images/event_img'
        news_img:
            uri_prefix: /images/news_img
            upload_destination: '%kernel.project_dir%/public/images/news_img'
        gallery_img:
            uri_prefix: /images/gallery_img
            upload_destination: '%kernel.project_dir%/public/images/gallery_img'
        music_file:
            uri_prefix: /music/file
            upload_destination: '%kernel.project_dir%/public/music/file'
        book_img:
            uri_prefix: /images/book_img
            upload_destination: '%kernel.project_dir%/public/images/book_img'

